source: https://github.com/marcelaritonang/ruang-diri-faq-ai

features:
  - node lts

nginx:
  root: public_html/public
  passenger:
    enabled: "on"
    app_env: "production"
    app_start_command: env PORT=$PORT node src/app.js

commands:
  - git pull origin main
  - filename: .env
    content: |
      PORT=29537
      NODE_ENV=production
      GEMINI_API_KEY=AIzaSyBA6nZvttt7M3dE11sj_f3-8_KF6J2iUkg
      WHATSAPP_PHONE_NUMBER_ID=929102273621555
      WHATSAPP_BUSINESS_ACCOUNT_ID=1948040609429233
      WHATSAPP_TOKEN=EAAUY6x5JlkwBQd4YJZBVAZBCZAZCZC4XF7UOK7ZATeWy0XLQxZBYwyOUaeaxGcUBLopWDqE8NQwCOcqV58jiOwlJZCvMZCEGU18mA02uv7jKqkSzRz2l6chhumqz7mi7BO6b0rDix3uoMaSQDqmbpx9ZByhRi85SP77ZCLcZCwX5MZARvmYGMlJ3nCJBRwr5dAdLZC
      WHATSAPP_VERIFY_TOKEN=alizhar123
  - npm install --production
  - mkdir -p tmp && touch tmp/restart.txt
