source: https://github.com/marcelaritonang/ruang-diri-faq-ai

features:
  - node lts

nginx:
  root: public_html/public
  passenger:
    enabled: "on"
    app_env: "production"
    app_start_command: env PORT=$PORT node src/app.js

commands:
  - filename: .env
    content: |
      PORT=29537
      NODE_ENV=production
      GEMINI_API_KEY=AIzaSyBvONOieqfDOiadhCgActdMyeEOjSUSiqI
      WHATSAPP_PHONE_NUMBER_ID=929102273621555
      WHATSAPP_BUSINESS_ACCOUNT_ID=1948040609429233
      WHATSAPP_TOKEN=EAAUY6x5JlkwBQTQaxsyyNQFeYGjtUeGgrJeqx50n9bZCooB05tnViUu5q0TtlZBuNzPUuCmbuGguOMwWt5o6BzZC1A5tc0IfrZAbEs8WZCkgUuBOWuNzP6z3JJBDwzkGuOKA1lLdLBDfMZAkEiAIqdaWgLRMwyPokRbwLsIjndZAkUfa8UszaXuI2nEHOa3xbrWWBQUbrEF5SwQnw10sTHAz92PsgISM2vzR49HtxZAv1wyNMU7AEUs21PzBbvt02D9Jm2JwGbpYjuAnE4FDqzVJxzQY
      WHATSAPP_VERIFY_TOKEN=alizhar123
  - npm install --production
