source: https://github.com/marcelaritonang/ruang-diri-faq-ai

features:
  - node lts

nginx:
  root: public_html/public
  passenger:
    enabled: "on"
    app_env: "production"
    app_start_command: env PORT=$PORT node src/app.js

commands:
  - git pull origin main
  - filename: .env
    content: |
      PORT=29537
      NODE_ENV=production
      GEMINI_API_KEY=AIzaSyBvONOieqfDOiadhCgActdMyeEOjSUSiqI
      WHATSAPP_PHONE_NUMBER_ID=929102273621555
      WHATSAPP_BUSINESS_ACCOUNT_ID=1948040609429233
      WHATSAPP_TOKEN=EAAUY6x5JlkwBQRfxUrnfCtZCLu1fPU1ZCFZBbdppicBjWvapOo4NlZC6diKAiOQhRABYn23vS7BJeuqHXHHhB92sKhkAzlZAIWZAX3rhQLVhhZA9rQUQXO156qFPSyhnjDdfWAmFL5O7uof4rTdmrAZA3VW3SZAmsuExsOZA2iYYSAnoxrlxNUzT1dZCRLXUVElGRwZBEtK3DPI99WgmjQLzfjfmvKcRXEx6JgGAKWHRP2Iqf50SymTneWo0VIuVhhED5yw9F5WnRRV71urZAgAiO0qX9fqK0
      WHATSAPP_VERIFY_TOKEN=alizhar123
  - npm install --production
  - mkdir -p tmp && touch tmp/restart.txt
